### ISSUE TITLE
Nested placeholder parsed, no effect

### ISSUE THREAD

**Issue by scarlettcloud** [Tanguygab/Utils-PlaceholderAPI-Expansion#1]
Hi! I'm hoping you can help me ensure I'm using the correct syntax for nested placeholders. Apologies if this is the wrong forum - I couldn't find an associated Discord or support place but I'll happily ask there if there's a more appropriate place! 

I'm trying to parse a nested placeholder that will return the appropriate color based on a users Job (Jobs Reborn plugin). I'm using VentureChat, and adding the placeholders into the chat formatting so that each user's job is shown, hopefully colored appropriately. I've tried a few different formats, but none seem to return the right color formatting. The two placeholders I'd like to nest are:

%jobsr_user_job_(jname/number)% - Returns the player job 

%jobsr_chatcolor_(jname/number)% - Returns jobs chat color

so that the placeholder returns a different chat color value depending on the user's specific job.

Here's what I've tried:

%nested_jobsr_chatcolor_jobsr_user_job_1%testtext
%nested_3_jobsr_chatcolor_jobsr_user_job_1%testtext
%nested_<jobsr_chatcolor_jobsr_user_job_1>%testtext
%nested_<jobsr_chatcolor_<jobsr_user_job_1>%testtext

Am I missing something? Is this an issue?

**Comment by Tanguygab** [comment]
%nested_jobsr_chatcolor_{jobsr_user_job_1}%testtext
should work
